### ISSUE TITLE
Q: where can you purchase the MK114?

### ISSUE THREAD

**Issue by mullender** [hufman/esp32-beacon#1]
I have been looking for a esp32 based smart plug, specifically for the bluetooth and wifi combination which is perfect for home assistant. 

But I have not been able to find one, hopefully you can point me in the right direction.

**Comment by hufman** [comment]
I obtained mine through [Alibaba](https://www.alibaba.com/products/mk114/CID205775510.html?IndexArea=product_en), or you could contact the manufacturer directly from the [product page](https://www.mokosmart.com/smart-home-wifi-plug-mk114/). I haven't found any other places though.

**Comment by mullender** [comment]
I had been looking on aliexpress, and could not find any. 
Thank you for pointing me in the right direction, I found a few now!
