### ISSUE TITLE
How do you flash the MK114 with ESPHome?

### ISSUE THREAD

**Issue by mvgijssel** [hufman/esp32-beacon#2]
I've been experimenting with bluetooth object tracking with ESPHome (https://github.com/mvgijssel/setup/issues/132) and the Shelly 1 PM Plus, but noticed that in some areas of my house I lack coverage so was investigating if I can add ESP32 based smart plugs and found this project! I see there are a ton of Moko devices available on Alibaba, but I'm unable to find any info how to get custom firmware on the device. How did you achieve this?

**Comment by hufman** [comment]
As part of the ordering process from MokoSmart, they sent me a link to a [datasheet](http://doc.mokotechnology.com/index.php?s=/page/165) and [schematic](http://doc.mokotechnology.com/index.php?s=/page/150) that indicates the ESP UART pads (which they call test points). After soldering some leads to them, ESPHome can be flashed just like normal (and then OTA flashing is convenient for later changes).

**Comment by mvgijssel** [comment]
> As part of the ordering process from MokoSmart, they sent me a link to a [datasheet](http://doc.mokotechnology.com/index.php?s=/page/165) and [schematic](http://doc.mokotechnology.com/index.php?s=/page/150) that indicates the ESP UART pads (which they call test points). After soldering some leads to them, ESPHome can be flashed just like normal (and then OTA flashing is convenient for later changes).

Ah nice, that helps a lot! Thanks!

**Comment by hufman** [comment]
Glad to help! Keep me updated with your ESPresence testing, I haven't had good luck just using the strongest ESP32 signal received for a given beacon.

**Comment by mvgijssel** [comment]
> Glad to help! Keep me updated with your ESPresence testing, I haven't had good luck just using the strongest ESP32 signal received for a given beacon.

Yeah didn’t have any luck with the regular ESPresence as wel, the detected object tends to jump between rooms a lot. If I would connect it to the lights, it would be a true disco 🤣. 

But recently I discovered https://github.com/ESPresense/ad-espresense-ips which tries to solve this by using trilateralization, which up to now looks promising! Just need to have ble scanners in the corners of my house and then I think I can have decent occupancy detection (for the larger areas).
